name: CI Shared

on:
  workflow_call:
    inputs:
      client_target:
        required: true
        type: string
      tag_name:
        required: false
        type: string

env:
  platform: "${{ inputs.client_target == 'emu' && 'Win32' || 'x64' }}"

jobs:
  build:
    if: github.repository == 'aquietone/macroquest'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MQ_PAT }}

      - name: Checkout submodules excluding eqlib
        run: git -c submodule."src/eqlib".update=none submodule update --init --recursive --depth=1

      - name: Checkout ${{ inputs.client_target }} eqlib
        run: |
          git submodule update --init --remote "src\eqlib"
          git -C src/eqlib checkout ${{ inputs.client_target }}

      - name: Checkout E3NextAndMQNextBinary for Mono artifacts
        if: inputs.tag_name == 'rel-e3n'
        run: |
          git clone https://github.com/RekkasGit/E3NextAndMQNextBinary
          Copy-Item .\E3NextAndMQNextBinary\resources\Mono -Destination .\data\resources\ -Recurse -Force
          Copy-Item .\E3NextAndMQNextBinary\config\* -Destination .\data\config\ -Recurse -Force
          Copy-Item .\E3NextAndMQNextBinary\macros\* -Destination .\data\macros\ -Recurse -Force
          Copy-Item .\E3NextAndMQNextBinary\mono-2.0-sgen.dll -Destination .\data\ -Recurse -Force
          Copy-Item .\E3NextAndMQNextBinary\eqbcs.exe -Destination .\data\ -Recurse -Force
          Copy-Item .\E3NextAndMQNextBinary\Utilities -Destination .\data\ -Recurse -Force
          Remove-Item -LiteralPath ".\E3NextAndMQNextBinary" -Force -Recurse

      - name: Download E3Next
        if: inputs.tag_name == 'rel-e3n'
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "RekkasGit/E3Next"
          latest: true
          fileName: "e3.zip"
          tarBall: false
          zipBall: false
          extract: true
          out-file-path: e3

      - name: Copy E3Next Release
        if: inputs.tag_name == 'rel-e3n'
        run: |
          New-Item .\data\mono\macros -ItemType Directory -ea 0
          Remove-Item -LiteralPath ".\e3\e3.zip" -Force
          Move-Item -Path .\e3 -Destination .\data\mono\macros\
          .\tools\streams64.exe -accepteula -s -d *.*

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: vcpkg Cache
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: |
            contrib/vcpkg/buildtrees
            contrib/vcpkg/downloads
            contrib/vcpkg/installed
            contrib/vcpkg/packages
            contrib/vcpkg/vcpkg.exe
            contrib/vcpkg/vcpkg_mq_last_bootstrap*.txt
          key: ${{ runner.os }}-vcpkg-${{ env.platform }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-${{ env.platform }}-
            ${{ runner.os }}-vcpkg-

      - name: Build ${{ env.platform }} Release
        run: msbuild src/MacroQuest.sln /NoLogo /Verbosity:minimal /p:Configuration=Release /p:Platform=${{ env.platform }}
      - name: Remove symbol files
        run: |
          Remove-Item .\build\bin\release\*.pdb
          Remove-Item .\build\bin\release\*.exp
          Remove-Item .\build\bin\release\*.lib
          Remove-Item .\build\bin\release\plugins\*.pdb
          Remove-Item .\build\bin\release\plugins\*.exp
          Remove-Item .\build\bin\release\plugins\*.lib
      - run: Compress-Archive -Path build/bin/release/* -Destination release.zip
        if: inputs.tag_name == 'rel-e3n'
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        if: inputs.tag_name == 'rel-e3n'
        with:
          name: release-zip
          path: release.zip
          retention-days: 1